apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner
  namespace: argocd
spec:
  destination:
    namespace: drone
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drone-runner-kube
    helm:
      values: |-
        env:
          DRONE_NAMESPACE_DEFAULT: drone
          DRONE_RPC_HOST: drone
          DRONE_RPC_PROTO: http
          DRONE_RPC_SECRET: ad562ccad33c0f98de659f6fb2efc36c
        rbac:
          buildNamespaces:
            - drone
    repoURL: https://charts.drone.io
    targetRevision: 0.1.x
