kind: pipeline
name: default
type: kubernetes

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    platforms:
      - linux/arm64
      - linux/amd64
    repo: git.local/gitea/nyancat
    tags: [ "${DRONE_COMMIT_SHA:0:7}","alpine" ]
    username:
      from_secret: gitea_username
    password:
      from_secret: gitea_password

- name: deploy
  image: jonasbg/yq
  commands:
  - git config --global user.name "DroneCI"
  - git config --global user.email "droneci@torden.tech"
  - git clone https://jonasbg:$GIT_PAT@git.local/gitea/gitOps.git gitOps
  - cd gitOps
  - git switch main
  - echo "Image tag"
  - export IMAGE_TAG="jonasbg/grimsgaard:${DRONE_COMMIT_SHA:0:7}"
  - yq eval -i '.spec.template.spec.containers[0]."image"=env(IMAGE_TAG)' cluster/project/nyan/nyan.yml
  - git commit -am "IMAGE_TAG CHANGED $IMAGE_TAG"
  - git push
  environment:
    GIT_PAT:
      from_secret: gitea_pat
  depends_on:
    - publish
