---
kind: pipeline
type: kubernetes
name: go-1-18

clone:
  skip_verify: true

steps:
- name: test
  image: golang:1.18
  commands:
  - go test -v src/intutils_test.go
  - go test -bench=. src/intutils_test.go

---
kind: pipeline
type: kubernetes
name: go-1-17

clone:
  skip_verify: true

steps:
- name: test
  image: golang:1.17
  commands:
  - go test -v src/intutils_test.go
  - go test -bench=. src/intutils_test.go
---
kind: pipeline
type: kubernetes
name: go-1-16

clone:
  skip_verify: true

steps:
- name: test
  image: golang:1.16
  commands:
  - go test -v src/intutils_test.go
  - go test -bench=. src/intutils_test.go
