apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: projects/
    repoURL: 'https://github.com/jonasbg/gitOps-nnug-demo.git'
    targetRevision: gitea
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
