apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitea
    helm:
      valueFiles:
      - values.yaml
      values: |-
        gitea:
          config:
            database:
              DB_TYPE: sqlite3
          admin:
            password: "r8sA8CPHD9!bt6d"
        memcached:
          enabled: false
        postgresql:
          enabled: false
        ingress:
          hosts:
          - host: 192.168.64.5:3000
    repoURL: https://dl.gitea.io/charts
    targetRevision: 5.x
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
